package io.redox.apt;

import io.redox.annotation.DoxProperty;
import io.redox.annotation.DoxSerializable;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.*;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;

/**
 * Generates a zero-reflection JSON converter for every {@code @DoxSerializable} class.
 *
 * Each annotated class {@code com.example.Foo} produces:
 * {@code com.example.FooDoxConverter} implementing {@code DoxConverter<Foo>}.
 *
 * Nested (static inner) classes follow the naming convention:
 * {@code com.example.Outer$Inner} → {@code com.example.Outer_InnerDoxConverter}
 */
@SupportedAnnotationTypes("io.redox.annotation.DoxSerializable")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class DoxAnnotationProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element el : roundEnv.getElementsAnnotatedWith(DoxSerializable.class)) {
            if (el.getKind() == ElementKind.CLASS) {
                try {
                    generateConverter((TypeElement) el);
                } catch (IOException e) {
                    processingEnv.getMessager().printMessage(
                            javax.tools.Diagnostic.Kind.ERROR,
                            "REDox APT failed for " + el + ": " + e.getMessage(), el);
                }
            }
        }
        return true;
    }

    // ── Code generation ────────────────────────────────────────────────────

    private void generateConverter(TypeElement typeEl) throws IOException {
        String packageName  = packageOf(typeEl);
        String flatName     = flatClassName(typeEl, packageName); // e.g. "Outer_Inner"
        String converterName = flatName + "DoxConverter";
        String converterFqn = packageName.isEmpty() ? converterName : packageName + "." + converterName;

        String targetFqn   = typeEl.getQualifiedName().toString(); // canonical, dots for nesting
        String targetRef   = targetFqn; // usable in source (same package, fully qualified)

        List<FieldInfo> fields = collectFields(typeEl);

        JavaFileObject jfo = processingEnv.getFiler().createSourceFile(converterFqn, typeEl);
        try (PrintWriter w = new PrintWriter(jfo.openWriter())) {
            if (!packageName.isEmpty()) w.println("package " + packageName + ";");
            w.println();
            w.println("// AUTO-GENERATED by REDox APT — do not edit");
            w.println("public final class " + converterName
                    + " implements io.redox.json.DoxConverter<" + targetRef + "> {");
            w.println();
            w.println("    public static final " + converterName + " INSTANCE = new " + converterName + "();");
            w.println();
            // ── Pre-encoded key byte arrays (one allocation at class-load time) ──
            for (FieldInfo fi : fields) {
                w.println("    private static final byte[] " + keyConst(fi)
                        + " = io.redox.json.RawKey.encode(\"" + fi.jsonName + "\");");
            }
            w.println();
            w.println("    static {");
            w.println("        io.redox.json.DoxConverterRegistry.register(" + targetRef + ".class, INSTANCE);");
            w.println("    }");
            w.println();

            // ── deserialize: iterate properties, compare raw bytes (zero String alloc) ──
            w.println("    @Override");
            w.println("    public " + targetRef + " deserialize(io.redox.core.DElement _element) {");
            w.println("        if (!_element.isValid() || _element.isNull()) return null;");
            w.println("        " + targetRef + " obj = new " + targetRef + "();");
            w.println("        for (io.redox.core.DProperty _p : _element.asObject()) {");
            w.println("            io.redox.core.DElement _k = _p.key();");
            boolean first = true;
            for (FieldInfo fi : fields) {
                String cond = (first ? "if" : "} else if") + " (_k.rawMatchesBytes(" + keyConst(fi) + ")) {";
                w.println("            " + cond);
                first = false;
                writeRawMatchBody(w, fi);
            }
            if (!fields.isEmpty()) w.println("            }");
            w.println("        }");
            w.println("        return obj;");
            w.println("    }");
            w.println();

            // ── serializeTo ───────────────────────────────────────────────
            w.println("    @Override");
            w.println("    public void serializeTo(" + targetRef + " obj, io.redox.json.JsonWriter _w) {");
            w.println("        if (obj == null) { _w.writeNull(); return; }");
            w.println("        _w.beginObject();");
            for (FieldInfo fi : fields) {
                writeFieldSerialize(w, fi);
            }
            w.println("        _w.endObject();");
            w.println("    }");
            w.println("}");
        }
    }

    // ── Deserialize code per field (rawMatchesBytes pattern) ─────────────

    /** Static field name for the pre-encoded key bytes of a field. */
    private String keyConst(FieldInfo fi) {
        return "_K_" + fi.jsonName.replaceAll("[^a-zA-Z0-9]", "_");
    }

    /**
     * Generates the body of an if-block for one field:
     *   io.redox.core.DElement _v = _p.value();
     *   obj.javaField = <expr>;
     */
    private void writeRawMatchBody(PrintWriter w, FieldInfo fi) {
        w.println("                io.redox.core.DElement _v = _p.value();");
        if (isList(fi.type)) {
            writeListDeserialize(w, (DeclaredType) fi.type, "_v", "obj." + fi.javaName,
                    "                ", 0);
        } else {
            w.println("                obj." + fi.javaName
                    + " = " + deserializeExprSimple(fi.type, "_v") + ";");
        }
    }

    private boolean isList(TypeMirror tm) {
        if (tm.getKind() != TypeKind.DECLARED) return false;
        return isList(((TypeElement)((DeclaredType)tm).asElement()).getQualifiedName().toString());
    }

    private String coerceToString(String var) {
        // Handles the case where JSON has a number/boolean where the POJO expects String
        return "(" + var + ".isString() || " + var + ".isNull()) ? "
                + var + ".getString() : "
                + var + ".isNumber() ? Double.toString(" + var + ".getDouble()) : "
                + "Boolean.toString(" + var + ".getBoolean())";
    }

    private void writeListDeserialize(PrintWriter w, DeclaredType listType, String srcVar,
                                       String target, String indent, int depth) {
        List<? extends TypeMirror> args = listType.getTypeArguments();
        TypeMirror elemType = args.isEmpty() ? null : args.get(0);

        String arrVar  = "_arr"  + depth;
        String listVar = "_list" + depth;
        String itemVar = "_item" + depth;

        w.println(indent + "if (" + srcVar + ".isNull()) { " + target + " = null; }");
        w.println(indent + "else if (" + srcVar + ".isArray()) {");
        w.println(indent + "    io.redox.core.DArray " + arrVar + " = " + srcVar + ".asArray();");

        String elemTypeName = (elemType != null) ? javaTypeName(elemType) : "Object";
        w.println(indent + "    java.util.List<" + elemTypeName + "> " + listVar
                + " = new java.util.ArrayList<>(" + arrVar + ".size());");
        w.println(indent + "    for (io.redox.core.DElement " + itemVar + " : " + arrVar + ") {");

        if (elemType != null && elemType.getKind() == TypeKind.DECLARED
                && isList(((TypeElement)((DeclaredType)elemType).asElement()).getQualifiedName().toString())) {
            // nested list
            String nestedTarget = listVar + ".add(???)"; // placeholder — will rewrite
            // use a temp variable approach
            String nestedVar = "_nested" + depth;
            w.println(indent + "        " + elemTypeName + " " + nestedVar + " = null;");
            writeListDeserialize(w, (DeclaredType) elemType, itemVar, nestedVar, indent + "        ", depth + 1);
            w.println(indent + "        " + listVar + ".add(" + nestedVar + ");");
        } else {
            String expr = (elemType != null) ? deserializeExprSimple(elemType, itemVar) : "null";
            w.println(indent + "        " + listVar + ".add(" + expr + ");");
        }

        w.println(indent + "    }");
        w.println(indent + "    " + target + " = " + listVar + ";");
        w.println(indent + "}");
    }

    /** Simplified expr generator used for list items (no block variant). */
    private String deserializeExprSimple(TypeMirror type, String var) {
        switch (type.getKind()) {
            case INT:     return var + ".getInt()";
            case LONG:    return var + ".getLong()";
            case DOUBLE:  return var + ".getDouble()";
            case FLOAT:   return "(float) " + var + ".getDouble()";
            case BOOLEAN: return var + ".getBoolean()";
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();
            if ("java.lang.String".equals(qn))  return coerceToString(var);
            if ("java.lang.Integer".equals(qn)) return var + ".getInt()";
            if ("java.lang.Long".equals(qn))    return var + ".getLong()";
            if ("java.lang.Double".equals(qn))  return var + ".getDouble()";
            if ("java.lang.Float".equals(qn))   return "(float) " + var + ".getDouble()";
            if ("java.lang.Boolean".equals(qn)) return var + ".getBoolean()";
            if (te.getAnnotation(DoxSerializable.class) != null) {
                return converterSimpleName(te) + ".INSTANCE.deserialize(" + var + ")";
            }
        }
        return "io.redox.json.JsonSerializer.bindElement(" + var + ", " + typeLiteral(type) + ")";
    }

    // ── Serialize code per field ───────────────────────────────────────────

    private void writeFieldSerialize(PrintWriter w, FieldInfo fi) {
        String jsonKey = fi.jsonName;
        String javaField = fi.javaName;
        w.println("        _w.writeKey(\"" + jsonKey + "\");");
        writeSerializeValue(w, fi.type, "obj." + javaField, "        ");
    }

    private void writeSerializeValue(PrintWriter w, TypeMirror type, String expr, String indent) {
        switch (type.getKind()) {
            case INT: case BYTE: case SHORT:
                w.println(indent + "_w.writeInt(" + expr + ");"); return;
            case LONG:
                w.println(indent + "_w.writeLong(" + expr + ");"); return;
            case DOUBLE:
                w.println(indent + "_w.writeDouble(" + expr + ");"); return;
            case FLOAT:
                w.println(indent + "_w.writeFloat(" + expr + ");"); return;
            case BOOLEAN:
                w.println(indent + "_w.writeBoolean(" + expr + ");"); return;
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();

            if ("java.lang.String".equals(qn)) {
                w.println(indent + "_w.writeStringOrNull(" + expr + ");"); return;
            }
            if ("java.lang.Integer".equals(qn) || "java.lang.Byte".equals(qn)
                    || "java.lang.Short".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeInt(" + expr + ");"); return;
            }
            if ("java.lang.Long".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeLong(" + expr + ");"); return;
            }
            if ("java.lang.Double".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeDouble(" + expr + ");"); return;
            }
            if ("java.lang.Float".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeFloat(" + expr + ");"); return;
            }
            if ("java.lang.Boolean".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeBoolean(" + expr + ");"); return;
            }
            if (isList(qn)) {
                writeListSerialize(w, dt, expr, indent, 0); return;
            }
            if (te.getAnnotation(DoxSerializable.class) != null) {
                w.println(indent + converterSimpleName(te) + ".INSTANCE.serializeTo(" + expr + ", _w);"); return;
            }
        }
        // fallback
        w.println(indent + "_w.writePojo(" + expr + ");");
    }

    private void writeListSerialize(PrintWriter w, DeclaredType listType, String expr,
                                     String indent, int depth) {
        List<? extends TypeMirror> args = listType.getTypeArguments();
        TypeMirror elemType = args.isEmpty() ? null : args.get(0);
        String itemVar = "_si" + depth;

        w.println(indent + "if (" + expr + " == null) { _w.writeNull(); }");
        w.println(indent + "else {");
        w.println(indent + "    _w.beginArray();");
        w.println(indent + "    for (" + (elemType != null ? javaTypeName(elemType) : "Object")
                + " " + itemVar + " : " + expr + ") {");
        w.println(indent + "        _w.nextArrayItem();");

        if (elemType != null && elemType.getKind() == TypeKind.DECLARED
                && isList(((TypeElement)((DeclaredType)elemType).asElement()).getQualifiedName().toString())) {
            writeListSerialize(w, (DeclaredType) elemType, itemVar, indent + "        ", depth + 1);
        } else {
            writeSerializeValue(w, elemType != null ? elemType : objectMirror(), itemVar, indent + "        ");
        }

        w.println(indent + "    }");
        w.println(indent + "    _w.endArray();");
        w.println(indent + "}");
    }

    // ── Field collection ───────────────────────────────────────────────────

    private List<FieldInfo> collectFields(TypeElement typeEl) {
        List<FieldInfo> result = new ArrayList<>();
        // Walk class + superclasses (excluding Object)
        TypeElement cur = typeEl;
        List<TypeElement> hierarchy = new ArrayList<>();
        while (cur != null && !cur.getQualifiedName().contentEquals("java.lang.Object")) {
            hierarchy.add(0, cur);
            TypeMirror superMirror = cur.getSuperclass();
            cur = (superMirror.getKind() == TypeKind.DECLARED)
                    ? (TypeElement) ((DeclaredType) superMirror).asElement()
                    : null;
        }
        for (TypeElement cls : hierarchy) {
            for (Element el : cls.getEnclosedElements()) {
                if (el.getKind() != ElementKind.FIELD) continue;
                VariableElement field = (VariableElement) el;
                Set<Modifier> mods = field.getModifiers();
                if (mods.contains(Modifier.STATIC) || mods.contains(Modifier.TRANSIENT)) continue;
                DoxProperty dp = field.getAnnotation(DoxProperty.class);
                if (dp != null && dp.ignore()) continue;
                String javaName = field.getSimpleName().toString();
                String jsonName = (dp != null && !dp.value().isEmpty()) ? dp.value() : javaName;
                result.add(new FieldInfo(javaName, jsonName, field.asType()));
            }
        }
        return result;
    }

    private static final class FieldInfo {
        final String javaName;
        final String jsonName;
        final TypeMirror type;
        FieldInfo(String javaName, String jsonName, TypeMirror type) {
            this.javaName = javaName; this.jsonName = jsonName; this.type = type;
        }
    }

    // ── Naming helpers ─────────────────────────────────────────────────────

    private String packageOf(TypeElement typeEl) {
        PackageElement pkg = processingEnv.getElementUtils().getPackageOf(typeEl);
        return pkg.isUnnamed() ? "" : pkg.getQualifiedName().toString();
    }

    private String flatClassName(TypeElement typeEl, String packageName) {
        String qualified = typeEl.getQualifiedName().toString();
        String afterPkg  = packageName.isEmpty() ? qualified
                : qualified.substring(packageName.length() + 1);
        return afterPkg.replace('.', '_');
    }

    private String converterSimpleName(TypeElement typeEl) {
        String pkg = packageOf(typeEl);
        String qualified = typeEl.getQualifiedName().toString();
        String afterPkg  = pkg.isEmpty() ? qualified : qualified.substring(pkg.length() + 1);
        return afterPkg.replace('.', '_') + "DoxConverter";
    }

    private String javaTypeName(TypeMirror tm) {
        if (tm == null) return "Object";
        switch (tm.getKind()) {
            case INT:     return "Integer";
            case LONG:    return "Long";
            case DOUBLE:  return "Double";
            case FLOAT:   return "Float";
            case BOOLEAN: return "Boolean";
            case BYTE:    return "Byte";
            case SHORT:   return "Short";
            case DECLARED: {
                DeclaredType dt = (DeclaredType) tm;
                StringBuilder sb = new StringBuilder(
                        ((TypeElement) dt.asElement()).getQualifiedName().toString());
                List<? extends TypeMirror> args = dt.getTypeArguments();
                if (!args.isEmpty()) {
                    sb.append('<');
                    for (int i = 0; i < args.size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(javaTypeName(args.get(i)));
                    }
                    sb.append('>');
                }
                return sb.toString();
            }
            default: return "Object";
        }
    }

    private String typeLiteral(TypeMirror tm) {
        if (tm.getKind() == TypeKind.DECLARED) {
            return ((TypeElement) ((DeclaredType) tm).asElement()).getQualifiedName() + ".class";
        }
        return "Object.class";
    }

    private boolean isList(String qualifiedName) {
        return "java.util.List".equals(qualifiedName)
            || "java.util.ArrayList".equals(qualifiedName)
            || "java.util.Collection".equals(qualifiedName);
    }

    private TypeMirror objectMirror() {
        return processingEnv.getElementUtils()
                .getTypeElement("java.lang.Object").asType();
    }
}
