package io.redox.apt;

import io.redox.annotation.DoxProperty;
import io.redox.annotation.DoxSerializable;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.*;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;

/**
 * Generates a zero-reflection JSON converter for every {@code @DoxSerializable} class.
 *
 * Each annotated class {@code com.example.Foo} produces:
 * {@code com.example.FooDoxConverter} implementing {@code DoxConverter<Foo>}.
 *
 * Nested (static inner) classes follow the naming convention:
 * {@code com.example.Outer$Inner} → {@code com.example.Outer_InnerDoxConverter}
 */
@SupportedAnnotationTypes("io.redox.annotation.DoxSerializable")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class DoxAnnotationProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element el : roundEnv.getElementsAnnotatedWith(DoxSerializable.class)) {
            if (el.getKind() == ElementKind.CLASS) {
                try {
                    generateConverter((TypeElement) el);
                } catch (IOException e) {
                    processingEnv.getMessager().printMessage(
                            javax.tools.Diagnostic.Kind.ERROR,
                            "REDox APT failed for " + el + ": " + e.getMessage(), el);
                }
            }
        }
        return true;
    }

    // ── Code generation ────────────────────────────────────────────────────

    private void generateConverter(TypeElement typeEl) throws IOException {
        String packageName  = packageOf(typeEl);
        String flatName     = flatClassName(typeEl, packageName); // e.g. "Outer_Inner"
        String converterName = flatName + "DoxConverter";
        String converterFqn = packageName.isEmpty() ? converterName : packageName + "." + converterName;

        String targetFqn   = typeEl.getQualifiedName().toString(); // canonical, dots for nesting
        String targetRef   = targetFqn; // usable in source (same package, fully qualified)

        List<FieldInfo> fields = collectFields(typeEl);

        JavaFileObject jfo = processingEnv.getFiler().createSourceFile(converterFqn, typeEl);
        try (PrintWriter w = new PrintWriter(jfo.openWriter())) {
            if (!packageName.isEmpty()) w.println("package " + packageName + ";");
            w.println();
            w.println("// AUTO-GENERATED by REDox APT — do not edit");
            w.println("public final class " + converterName
                    + " implements io.redox.json.DoxConverter<" + targetRef + ">,"
                    + " io.redox.json.StreamBindable<" + targetRef + "> {");
            w.println();
            w.println("    public static final " + converterName + " INSTANCE = new " + converterName + "();");
            w.println();
            w.println("    // Unsafe singleton — null if unavailable (fallback to direct assignment)");
            w.println("    private static final sun.misc.Unsafe _U = io.redox.json.UnsafeAccess.UNSAFE;");
            w.println();
            // ── Pre-encoded key byte arrays ──
            for (FieldInfo fi : fields) {
                w.println("    private static final byte[] " + keyConst(fi)
                        + " = io.redox.json.RawKey.encode(\"" + fi.jsonName + "\");");
            }
            // ── Unsafe field offsets for primitive fields ──
            boolean hasPrimitive = fields.stream().anyMatch(fi -> isPrimitiveKind(fi.type));
            if (hasPrimitive) {
                w.println();
                for (FieldInfo fi : fields) {
                    if (isPrimitiveKind(fi.type)) {
                        w.println("    private static final long " + offConst(fi)
                                + " = (_U != null) ? io.redox.json.UnsafeAccess.fieldOffset("
                                + targetRef + ".class, \"" + fi.javaName + "\") : -1L;");
                    }
                }
            }
            w.println();
            w.println("    static {");
            w.println("        io.redox.json.DoxConverterRegistry.register(" + targetRef + ".class, INSTANCE);");
            w.println("    }");
            w.println();

            // ── deserialize: iterate properties, compare raw bytes (zero String alloc) ──
            w.println("    @Override");
            w.println("    public " + targetRef + " deserialize(io.redox.core.DElement _element) {");
            w.println("        if (!_element.isValid() || _element.isNull()) return null;");
            w.println("        " + targetRef + " obj = new " + targetRef + "();");
            w.println("        for (io.redox.core.DProperty _p : _element.asObject()) {");
            w.println("            io.redox.core.DElement _k = _p.key();");
            boolean first = true;
            for (FieldInfo fi : fields) {
                String cond = (first ? "if" : "} else if") + " (_k.rawMatchesBytes(" + keyConst(fi) + ")) {";
                w.println("            " + cond);
                first = false;
                writeRawMatchBody(w, fi);
            }
            if (!fields.isEmpty()) w.println("            }");
            w.println("        }");
            w.println("        return obj;");
            w.println("    }");
            w.println();

            // ── serializeTo ───────────────────────────────────────────────
            w.println("    @Override");
            w.println("    public void serializeTo(" + targetRef + " obj, io.redox.json.JsonWriter _w) {");
            w.println("        if (obj == null) { _w.writeNull(); return; }");
            w.println("        _w.beginObject();");
            for (FieldInfo fi : fields) {
                writeFieldSerialize(w, fi);
            }
            w.println("        _w.endObject();");
            w.println("    }");
            w.println();

            // ── bindDirect ────────────────────────────────────────────────
            w.println("    @Override");
            w.println("    public " + targetRef
                    + " bindDirect(byte[] _src, int _off, int _len) {");
            w.println("        io.redox.json.JsonStreamParser _p ="
                    + " new io.redox.json.JsonStreamParser(_src, _off, _len);");
            w.println("        _p.nextToken();");
            w.println("        return bindFromParser(_p);");
            w.println("    }");
            w.println();

            // ── bindFromParser ────────────────────────────────────────────
            w.println("    @Override");
            w.println("    public " + targetRef
                    + " bindFromParser(io.redox.json.JsonStreamParser _p) {");
            w.println("        if (_p.currentToken() == io.redox.json.JsonStreamParser.Token.VALUE_NULL) return null;");
            w.println("        " + targetRef + " obj = new " + targetRef + "();");
            w.println("        while (_p.nextToken() != io.redox.json.JsonStreamParser.Token.END_OBJECT) {");
            boolean firstStream = true;
            for (FieldInfo fi : fields) {
                String cond = (firstStream ? "if" : "} else if")
                        + " (_p.keyMatchesBytes(" + keyConst(fi) + ")) {";
                w.println("            " + cond);
                firstStream = false;
                writeStreamFieldBody(w, fi);
            }
            if (!fields.isEmpty()) {
                w.println("            } else {");
                w.println("                _p.nextToken(); _p.skipValue();");
                w.println("            }");
            }
            w.println("        }");
            w.println("        return obj;");
            w.println("    }");

            // ── stream list helper methods ────────────────────────────────
            for (FieldInfo fi : fields) {
                if (isList(fi.type)) {
                    writeStreamListHelper(w, fi.javaName, (DeclaredType) fi.type, 0);
                }
            }

            w.println("}");
        }
    }

    // ── Stream field body (single-pass binding) ───────────────────────────

    /**
     * Generates the body of one key-matched branch in bindFromParser.
     * At entry: parser is positioned at FIELD_KEY.
     * We must advance to the value then assign.
     */
    private void writeStreamFieldBody(PrintWriter w, FieldInfo fi) {
        w.println("                _p.nextToken(); // advance to value");
        if (isList(fi.type)) {
            w.println("                if (_p.currentToken() == io.redox.json.JsonStreamParser.Token.VALUE_NULL) {");
            w.println("                    obj." + fi.javaName + " = null;");
            w.println("                } else {");
            w.println("                    obj." + fi.javaName + " = _sl_" + fi.javaName + "(_p);");
            w.println("                }");
        } else if (isPrimitiveKind(fi.type) && !isBoxedType(fi.type)) {
            // Unsafe raw write for primitive fields — eliminates null-check and type-check overhead.
            // Guard on _U != null (falls back to direct assignment on JVMs without Unsafe).
            String off = offConst(fi);
            String put = unsafePutCall(fi.type, "obj", off, streamValueExpr(fi.type));
            w.println("                if (_U != null && " + off + " >= 0L) { " + put + " }");
            w.println("                else { obj." + fi.javaName + " = " + streamValueExpr(fi.type) + "; }");
        } else {
            w.println("                obj." + fi.javaName + " = " + streamValueExpr(fi.type) + ";");
        }
    }

    /** Returns the Unsafe field offset constant name for a field. */
    private String offConst(FieldInfo fi) {
        return "_OFF_" + fi.javaName.replaceAll("[^a-zA-Z0-9]", "_");
    }

    /** True if the type is a Java primitive (int, long, double, float, boolean, byte, short). */
    private boolean isPrimitiveKind(TypeMirror tm) {
        switch (tm.getKind()) {
            case INT: case LONG: case DOUBLE: case FLOAT:
            case BOOLEAN: case BYTE: case SHORT: return true;
            default: return false;
        }
    }

    /** True for boxed types like Integer, Long, etc. */
    private boolean isBoxedType(TypeMirror tm) {
        if (tm.getKind() != TypeKind.DECLARED) return false;
        String qn = ((TypeElement)((DeclaredType)tm).asElement()).getQualifiedName().toString();
        return qn.startsWith("java.lang.") && (
                "java.lang.Integer".equals(qn) || "java.lang.Long".equals(qn) ||
                "java.lang.Double".equals(qn)  || "java.lang.Float".equals(qn) ||
                "java.lang.Boolean".equals(qn) || "java.lang.Byte".equals(qn) ||
                "java.lang.Short".equals(qn));
    }

    /** Returns the Unsafe.putXxx call for a primitive field write. */
    private String unsafePutCall(TypeMirror type, String obj, String offset, String value) {
        switch (type.getKind()) {
            case INT:     return "_U.putInt("     + obj + ", " + offset + ", " + value + ");";
            case LONG:    return "_U.putLong("    + obj + ", " + offset + ", " + value + ");";
            case DOUBLE:  return "_U.putDouble("  + obj + ", " + offset + ", " + value + ");";
            case FLOAT:   return "_U.putFloat("   + obj + ", " + offset + ", " + value + ");";
            case BOOLEAN: return "_U.putBoolean(" + obj + ", " + offset + ", " + value + ");";
            case BYTE:    return "_U.putByte("    + obj + ", " + offset + ", " + value + ");";
            case SHORT:   return "_U.putShort("   + obj + ", " + offset + ", " + value + ");";
            default:      return obj + ".field = " + value + ";";
        }
    }

    /**
     * Returns the expression to read the current parser value into a field of the given type.
     * Assumes _p.currentToken() is already the value token.
     */
    private String streamValueExpr(TypeMirror type) {
        switch (type.getKind()) {
            case INT:     return "_p.getInt()";
            case LONG:    return "_p.getLong()";
            case DOUBLE:  return "_p.getDouble()";
            case FLOAT:   return "(float) _p.getDouble()";
            case BOOLEAN: return "_p.getBoolean()";
            case BYTE:    return "(byte) _p.getInt()";
            case SHORT:   return "(short) _p.getInt()";
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();
            if ("java.lang.String".equals(qn))  return "_p.getStringCoerced()";
            if ("java.lang.Integer".equals(qn)) return "_p.getInt()";
            if ("java.lang.Long".equals(qn))    return "_p.getLong()";
            if ("java.lang.Double".equals(qn))  return "_p.getDouble()";
            if ("java.lang.Float".equals(qn))   return "(float) _p.getDouble()";
            if ("java.lang.Boolean".equals(qn)) return "_p.getBoolean()";
            if ("java.lang.Byte".equals(qn))    return "(byte) _p.getInt()";
            if ("java.lang.Short".equals(qn))   return "(short) _p.getInt()";
            if (te.getAnnotation(DoxSerializable.class) != null) {
                return converterSimpleName(te) + ".INSTANCE.bindFromParser(_p)";
            }
        }
        // fallback: use tape-based bindElement
        return "io.redox.json.JsonSerializer.bindElement("
                + "new io.redox.core.DElement(null,0,0), " + typeLiteral(type) + ")"; // placeholder
    }

    /**
     * Generates a private static helper: {@code _sl_fieldName(JsonStreamParser p)}
     * that reads a List from the stream (p.currentToken() == START_ARRAY).
     * Handles nested lists recursively by generating inner helpers with depth suffix.
     */
    private void writeStreamListHelper(PrintWriter w, String baseName,
                                        DeclaredType listType, int depth) {
        List<? extends TypeMirror> args = listType.getTypeArguments();
        TypeMirror elemType = args.isEmpty() ? null : args.get(0);
        String helperName = depth == 0 ? "_sl_" + baseName : "_sl_" + baseName + "_d" + depth;
        String elemTypeName = elemType != null ? javaTypeName(elemType) : "Object";
        String listTypeName = "java.util.List<" + elemTypeName + ">";

        w.println();
        w.println("    private static " + listTypeName + " " + helperName
                + "(io.redox.json.JsonStreamParser _p) {");
        w.println("        " + listTypeName + " _list = new java.util.ArrayList<>();");
        w.println("        io.redox.json.JsonStreamParser.Token _t;");
        w.println("        while ((_t = _p.nextToken()) !="
                + " io.redox.json.JsonStreamParser.Token.END_ARRAY) {");

        if (elemType == null) {
            w.println("            _list.add(null);");
        } else if (isList(elemType)) {
            // nested list: emit call to depth+1 helper (defined AFTER this method closes)
            String nestedHelper = "_sl_" + baseName + "_d" + (depth + 1);
            w.println("            if (_t == io.redox.json.JsonStreamParser.Token.VALUE_NULL) {");
            w.println("                _list.add(null);");
            w.println("            } else {");
            w.println("                _list.add(" + nestedHelper + "(_p));");
            w.println("            }");
            // recursive helper generation moved to AFTER this method closes
        } else if (elemType.getKind() == TypeKind.DECLARED
                && ((TypeElement)((DeclaredType)elemType).asElement())
                        .getAnnotation(DoxSerializable.class) != null) {
            // list of @DoxSerializable POJO
            TypeElement te = (TypeElement) ((DeclaredType) elemType).asElement();
            w.println("            _list.add(" + converterSimpleName(te)
                    + ".INSTANCE.bindFromParser(_p));");
        } else {
            // list of scalar/String
            w.println("            _list.add(" + streamItemExpr(elemType) + ");");
        }

        w.println("        }"); // close while
        w.println("        return _list;");
        w.println("    }"); // close method — nested helper written AFTER, not inside

        // recursively generate the nested helper as a sibling method
        if (elemType != null && isList(elemType)) {
            writeStreamListHelper(w, baseName, (DeclaredType) elemType, depth + 1);
        }
    }

    /** Like {@link #streamValueExpr} but for list item context (uses _t not _p.currentToken). */
    private String streamItemExpr(TypeMirror type) {
        switch (type.getKind()) {
            case INT:     return "(int) _p.getLong()";
            case LONG:    return "_p.getLong()";
            case DOUBLE:  return "_p.getDouble()";
            case FLOAT:   return "(float) _p.getDouble()";
            case BOOLEAN: return "_p.getBoolean()";
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();
            if ("java.lang.String".equals(qn))  return "_p.getStringCoerced()";
            if ("java.lang.Integer".equals(qn)) return "_p.getInt()";
            if ("java.lang.Long".equals(qn))    return "_p.getLong()";
            if ("java.lang.Double".equals(qn))  return "_p.getDouble()";
            if ("java.lang.Float".equals(qn))   return "(float) _p.getDouble()";
            if ("java.lang.Boolean".equals(qn)) return "_p.getBoolean()";
        }
        return "null";
    }

    // ── Deserialize code per field (rawMatchesBytes pattern) ─────────────

    /** Static field name for the pre-encoded key bytes of a field. */
    private String keyConst(FieldInfo fi) {
        return "_K_" + fi.jsonName.replaceAll("[^a-zA-Z0-9]", "_");
    }

    /**
     * Generates the body of an if-block for one field:
     *   io.redox.core.DElement _v = _p.value();
     *   obj.javaField = <expr>;
     */
    private void writeRawMatchBody(PrintWriter w, FieldInfo fi) {
        w.println("                io.redox.core.DElement _v = _p.value();");
        if (isList(fi.type)) {
            writeListDeserialize(w, (DeclaredType) fi.type, "_v", "obj." + fi.javaName,
                    "                ", 0);
        } else {
            w.println("                obj." + fi.javaName
                    + " = " + deserializeExprSimple(fi.type, "_v") + ";");
        }
    }

    private boolean isList(TypeMirror tm) {
        if (tm.getKind() != TypeKind.DECLARED) return false;
        return isList(((TypeElement)((DeclaredType)tm).asElement()).getQualifiedName().toString());
    }

    private String coerceToString(String var) {
        // Handles the case where JSON has a number/boolean where the POJO expects String
        return "(" + var + ".isString() || " + var + ".isNull()) ? "
                + var + ".getString() : "
                + var + ".isNumber() ? Double.toString(" + var + ".getDouble()) : "
                + "Boolean.toString(" + var + ".getBoolean())";
    }

    private void writeListDeserialize(PrintWriter w, DeclaredType listType, String srcVar,
                                       String target, String indent, int depth) {
        List<? extends TypeMirror> args = listType.getTypeArguments();
        TypeMirror elemType = args.isEmpty() ? null : args.get(0);

        String arrVar  = "_arr"  + depth;
        String listVar = "_list" + depth;
        String itemVar = "_item" + depth;

        w.println(indent + "if (" + srcVar + ".isNull()) { " + target + " = null; }");
        w.println(indent + "else if (" + srcVar + ".isArray()) {");
        w.println(indent + "    io.redox.core.DArray " + arrVar + " = " + srcVar + ".asArray();");

        String elemTypeName = (elemType != null) ? javaTypeName(elemType) : "Object";
        w.println(indent + "    java.util.List<" + elemTypeName + "> " + listVar
                + " = new java.util.ArrayList<>(" + arrVar + ".size());");
        w.println(indent + "    for (io.redox.core.DElement " + itemVar + " : " + arrVar + ") {");

        if (elemType != null && elemType.getKind() == TypeKind.DECLARED
                && isList(((TypeElement)((DeclaredType)elemType).asElement()).getQualifiedName().toString())) {
            // nested list
            String nestedTarget = listVar + ".add(???)"; // placeholder — will rewrite
            // use a temp variable approach
            String nestedVar = "_nested" + depth;
            w.println(indent + "        " + elemTypeName + " " + nestedVar + " = null;");
            writeListDeserialize(w, (DeclaredType) elemType, itemVar, nestedVar, indent + "        ", depth + 1);
            w.println(indent + "        " + listVar + ".add(" + nestedVar + ");");
        } else {
            String expr = (elemType != null) ? deserializeExprSimple(elemType, itemVar) : "null";
            w.println(indent + "        " + listVar + ".add(" + expr + ");");
        }

        w.println(indent + "    }");
        w.println(indent + "    " + target + " = " + listVar + ";");
        w.println(indent + "}");
    }

    /** Simplified expr generator used for list items (no block variant). */
    private String deserializeExprSimple(TypeMirror type, String var) {
        switch (type.getKind()) {
            case INT:     return var + ".getInt()";
            case LONG:    return var + ".getLong()";
            case DOUBLE:  return var + ".getDouble()";
            case FLOAT:   return "(float) " + var + ".getDouble()";
            case BOOLEAN: return var + ".getBoolean()";
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();
            if ("java.lang.String".equals(qn))  return coerceToString(var);
            if ("java.lang.Integer".equals(qn)) return var + ".getInt()";
            if ("java.lang.Long".equals(qn))    return var + ".getLong()";
            if ("java.lang.Double".equals(qn))  return var + ".getDouble()";
            if ("java.lang.Float".equals(qn))   return "(float) " + var + ".getDouble()";
            if ("java.lang.Boolean".equals(qn)) return var + ".getBoolean()";
            if (te.getAnnotation(DoxSerializable.class) != null) {
                return converterSimpleName(te) + ".INSTANCE.deserialize(" + var + ")";
            }
        }
        return "io.redox.json.JsonSerializer.bindElement(" + var + ", " + typeLiteral(type) + ")";
    }

    // ── Serialize code per field ───────────────────────────────────────────

    private void writeFieldSerialize(PrintWriter w, FieldInfo fi) {
        String jsonKey = fi.jsonName;
        String javaField = fi.javaName;
        w.println("        _w.writeKey(\"" + jsonKey + "\");");
        writeSerializeValue(w, fi.type, "obj." + javaField, "        ");
    }

    private void writeSerializeValue(PrintWriter w, TypeMirror type, String expr, String indent) {
        switch (type.getKind()) {
            case INT: case BYTE: case SHORT:
                w.println(indent + "_w.writeInt(" + expr + ");"); return;
            case LONG:
                w.println(indent + "_w.writeLong(" + expr + ");"); return;
            case DOUBLE:
                w.println(indent + "_w.writeDouble(" + expr + ");"); return;
            case FLOAT:
                w.println(indent + "_w.writeFloat(" + expr + ");"); return;
            case BOOLEAN:
                w.println(indent + "_w.writeBoolean(" + expr + ");"); return;
            default: break;
        }
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType dt = (DeclaredType) type;
            TypeElement te = (TypeElement) dt.asElement();
            String qn = te.getQualifiedName().toString();

            if ("java.lang.String".equals(qn)) {
                w.println(indent + "_w.writeStringOrNull(" + expr + ");"); return;
            }
            if ("java.lang.Integer".equals(qn) || "java.lang.Byte".equals(qn)
                    || "java.lang.Short".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeInt(" + expr + ");"); return;
            }
            if ("java.lang.Long".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeLong(" + expr + ");"); return;
            }
            if ("java.lang.Double".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeDouble(" + expr + ");"); return;
            }
            if ("java.lang.Float".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeFloat(" + expr + ");"); return;
            }
            if ("java.lang.Boolean".equals(qn)) {
                w.println(indent + "if (" + expr + " == null) _w.writeNull(); else _w.writeBoolean(" + expr + ");"); return;
            }
            if (isList(qn)) {
                writeListSerialize(w, dt, expr, indent, 0); return;
            }
            if (te.getAnnotation(DoxSerializable.class) != null) {
                w.println(indent + converterSimpleName(te) + ".INSTANCE.serializeTo(" + expr + ", _w);"); return;
            }
        }
        // fallback
        w.println(indent + "_w.writePojo(" + expr + ");");
    }

    private void writeListSerialize(PrintWriter w, DeclaredType listType, String expr,
                                     String indent, int depth) {
        List<? extends TypeMirror> args = listType.getTypeArguments();
        TypeMirror elemType = args.isEmpty() ? null : args.get(0);
        String itemVar = "_si" + depth;

        w.println(indent + "if (" + expr + " == null) { _w.writeNull(); }");
        w.println(indent + "else {");
        w.println(indent + "    _w.beginArray();");
        w.println(indent + "    for (" + (elemType != null ? javaTypeName(elemType) : "Object")
                + " " + itemVar + " : " + expr + ") {");
        w.println(indent + "        _w.nextArrayItem();");

        if (elemType != null && elemType.getKind() == TypeKind.DECLARED
                && isList(((TypeElement)((DeclaredType)elemType).asElement()).getQualifiedName().toString())) {
            writeListSerialize(w, (DeclaredType) elemType, itemVar, indent + "        ", depth + 1);
        } else {
            writeSerializeValue(w, elemType != null ? elemType : objectMirror(), itemVar, indent + "        ");
        }

        w.println(indent + "    }");
        w.println(indent + "    _w.endArray();");
        w.println(indent + "}");
    }

    // ── Field collection ───────────────────────────────────────────────────

    private List<FieldInfo> collectFields(TypeElement typeEl) {
        List<FieldInfo> result = new ArrayList<>();
        // Walk class + superclasses (excluding Object)
        TypeElement cur = typeEl;
        List<TypeElement> hierarchy = new ArrayList<>();
        while (cur != null && !cur.getQualifiedName().contentEquals("java.lang.Object")) {
            hierarchy.add(0, cur);
            TypeMirror superMirror = cur.getSuperclass();
            cur = (superMirror.getKind() == TypeKind.DECLARED)
                    ? (TypeElement) ((DeclaredType) superMirror).asElement()
                    : null;
        }
        for (TypeElement cls : hierarchy) {
            for (Element el : cls.getEnclosedElements()) {
                if (el.getKind() != ElementKind.FIELD) continue;
                VariableElement field = (VariableElement) el;
                Set<Modifier> mods = field.getModifiers();
                if (mods.contains(Modifier.STATIC) || mods.contains(Modifier.TRANSIENT)) continue;
                DoxProperty dp = field.getAnnotation(DoxProperty.class);
                if (dp != null && dp.ignore()) continue;
                String javaName = field.getSimpleName().toString();
                String jsonName = (dp != null && !dp.value().isEmpty()) ? dp.value() : javaName;
                result.add(new FieldInfo(javaName, jsonName, field.asType()));
            }
        }
        return result;
    }

    private static final class FieldInfo {
        final String javaName;
        final String jsonName;
        final TypeMirror type;
        FieldInfo(String javaName, String jsonName, TypeMirror type) {
            this.javaName = javaName; this.jsonName = jsonName; this.type = type;
        }
    }

    // ── Naming helpers ─────────────────────────────────────────────────────

    private String packageOf(TypeElement typeEl) {
        PackageElement pkg = processingEnv.getElementUtils().getPackageOf(typeEl);
        return pkg.isUnnamed() ? "" : pkg.getQualifiedName().toString();
    }

    private String flatClassName(TypeElement typeEl, String packageName) {
        String qualified = typeEl.getQualifiedName().toString();
        String afterPkg  = packageName.isEmpty() ? qualified
                : qualified.substring(packageName.length() + 1);
        return afterPkg.replace('.', '_');
    }

    private String converterSimpleName(TypeElement typeEl) {
        String pkg = packageOf(typeEl);
        String qualified = typeEl.getQualifiedName().toString();
        String afterPkg  = pkg.isEmpty() ? qualified : qualified.substring(pkg.length() + 1);
        return afterPkg.replace('.', '_') + "DoxConverter";
    }

    private String javaTypeName(TypeMirror tm) {
        if (tm == null) return "Object";
        switch (tm.getKind()) {
            case INT:     return "Integer";
            case LONG:    return "Long";
            case DOUBLE:  return "Double";
            case FLOAT:   return "Float";
            case BOOLEAN: return "Boolean";
            case BYTE:    return "Byte";
            case SHORT:   return "Short";
            case DECLARED: {
                DeclaredType dt = (DeclaredType) tm;
                StringBuilder sb = new StringBuilder(
                        ((TypeElement) dt.asElement()).getQualifiedName().toString());
                List<? extends TypeMirror> args = dt.getTypeArguments();
                if (!args.isEmpty()) {
                    sb.append('<');
                    for (int i = 0; i < args.size(); i++) {
                        if (i > 0) sb.append(", ");
                        sb.append(javaTypeName(args.get(i)));
                    }
                    sb.append('>');
                }
                return sb.toString();
            }
            default: return "Object";
        }
    }

    private String typeLiteral(TypeMirror tm) {
        if (tm.getKind() == TypeKind.DECLARED) {
            return ((TypeElement) ((DeclaredType) tm).asElement()).getQualifiedName() + ".class";
        }
        return "Object.class";
    }

    private boolean isList(String qualifiedName) {
        return "java.util.List".equals(qualifiedName)
            || "java.util.ArrayList".equals(qualifiedName)
            || "java.util.Collection".equals(qualifiedName);
    }

    private TypeMirror objectMirror() {
        return processingEnv.getElementUtils()
                .getTypeElement("java.lang.Object").asType();
    }
}
